import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseSync, type ESTree, type Plugin, Visitor } from "vite-plus";

interface WorkTags {
  [name: string]: number;
}

const readWorkTagValue = (expression: ESTree.Expression): number => {
  if (expression.type === "Literal" && typeof expression.value === "number") {
    return expression.value;
  }
  if (
    expression.type === "UnaryExpression" &&
    expression.operator === "-" &&
    expression.argument.type === "Literal" &&
    typeof expression.argument.value === "number"
  ) {
    return -expression.argument.value;
  }
  throw new Error("React DevTools contains a non-numeric work tag");
};

const readWorkTags = (expression: ESTree.ObjectExpression): WorkTags => {
  const workTags: WorkTags = {};
  for (const property of expression.properties) {
    if (
      property.type !== "Property" ||
      property.kind !== "init" ||
      property.computed ||
      property.key.type !== "Identifier"
    ) {
      throw new Error("React DevTools contains an unsupported work-tag property");
    }
    workTags[property.key.name] = readWorkTagValue(property.value);
  }
  return workTags;
};

const readReactDevToolsWorkTags = (): WorkTags[] => {
  const require = createRequire(import.meta.url);
  const packagePath = require.resolve("react-devtools-core/package.json");
  const backendPath = resolve(dirname(packagePath), "dist/backend.js");
  const parseResult = parseSync(backendPath, readFileSync(backendPath, "utf8"), {
    lang: "js",
    sourceType: "script",
  });
  if (parseResult.errors.length > 0) {
    throw new Error(`Oxc could not parse React DevTools: ${parseResult.errors[0]?.message}`);
  }

  const workTagMaps: WorkTags[] = [];
  new Visitor({
    AssignmentExpression: (expression) => {
      if (
        expression.left.type === "Identifier" &&
        expression.left.name === "ReactTypeOfWork" &&
        expression.right.type === "ObjectExpression"
      ) {
        workTagMaps.push(readWorkTags(expression.right));
      }
    },
  }).visit(parseResult.program);

  if (workTagMaps.length < 2) {
    throw new Error("React DevTools does not contain the expected work-tag tables");
  }
  return workTagMaps;
};

const validateWorkTags = (modernWorkTags: WorkTags, react17WorkTags: WorkTags): string[] => {
  const modernNames = Object.keys(modernWorkTags).sort();
  const react17Names = Object.keys(react17WorkTags).sort();
  if (modernNames.length === 0 || modernNames.join("\0") !== react17Names.join("\0")) {
    throw new Error("React DevTools work-tag tables are empty or have mismatched keys");
  }
  return modernNames;
};

const renderWorkTagMap = (name: string, names: string[], workTags: WorkTags): string =>
  [
    `export const ${name} = {`,
    ...names.map((workTagName) => `  ${workTagName}: ${workTags[workTagName]},`),
    "} satisfies Readonly<ReactWorkTags>;",
  ].join("\n");

const renderGeneratedModule = (
  names: string[],
  modernWorkTags: WorkTags,
  react17WorkTags: WorkTags,
): string => {
  const modernWorkTagValues = [
    ...new Set(Object.values(modernWorkTags).filter((workTag) => workTag >= 0)),
  ].sort((leftWorkTag, rightWorkTag) => leftWorkTag - rightWorkTag);
  const constants = names
    .filter((name) => modernWorkTags[name] >= 0)
    .map((name) => `export const ${name}Tag = ${modernWorkTags[name]};`)
    .join("\n");
  const workTagUnion = modernWorkTagValues.map((workTag) => `  | ${workTag}`).join("\n");

  return [
    "// Generated by the React internals Vite+ plugin from react-devtools-core.",
    "",
    "export interface ReactWorkTags {",
    ...names.map((name) => `  ${name}: number;`),
    "}",
    "",
    constants,
    "",
    renderWorkTagMap("React17WorkTags", names, react17WorkTags),
    "",
    renderWorkTagMap("ModernReactWorkTags", names, modernWorkTags),
    "",
    "export type ModernReactWorkTag =",
    `${workTagUnion};`,
    "",
    "export type HostWorkTag =",
    "  | typeof HostComponentTag",
    "  | typeof HostHoistableTag",
    "  | typeof HostSingletonTag",
    "  | typeof HostTextTag;",
    "",
    "export const getReactWorkTags = (version: string): Readonly<ReactWorkTags> =>",
    "  /^17\\.0\\.(?:0|1)(?:\\D|$)/.test(version) ? React17WorkTags : ModernReactWorkTags;",
    "",
  ].join("\n");
};

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const generatedModulePath = resolve(scriptDirectory, "../src/generated/react-work-tags.ts");

const generateReactInternals = (): void => {
  const [modernWorkTags, react17WorkTags] = readReactDevToolsWorkTags();
  const names = validateWorkTags(modernWorkTags, react17WorkTags);
  const generatedModule = renderGeneratedModule(names, modernWorkTags, react17WorkTags);
  const existingModule = existsSync(generatedModulePath)
    ? readFileSync(generatedModulePath, "utf8")
    : undefined;

  if (existingModule === generatedModule) return;
  if (process.env.CI) {
    throw new Error("Generated React internals are stale; run nr build and commit the result");
  }
  mkdirSync(dirname(generatedModulePath), { recursive: true });
  writeFileSync(generatedModulePath, generatedModule);
};

export const reactInternalsPlugin = (): Plugin => {
  let didGenerateReactInternals = false;
  return {
    name: "bippy-react-internals",
    buildStart: () => {
      if (didGenerateReactInternals) return;
      generateReactInternals();
      didGenerateReactInternals = true;
    },
  };
};
