import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseSync, type ESTree, type Plugin, Visitor } from "vite-plus";

interface WorkTags {
  [name: string]: number;
}

const generatedModuleLineWidth = 100;

const readWorkTagValue = (expression: ESTree.Expression): number => {
  if (expression.type === "Literal" && typeof expression.value === "number") {
    return expression.value;
  }
  if (
    expression.type === "UnaryExpression" &&
    expression.operator === "-" &&
    expression.argument.type === "Literal" &&
    typeof expression.argument.value === "number"
  ) {
    return -expression.argument.value;
  }
  throw new Error("React DevTools contains a non-numeric work tag");
};

const readWorkTags = (expression: ESTree.ObjectExpression): WorkTags => {
  const workTags: WorkTags = {};
  for (const property of expression.properties) {
    if (
      property.type !== "Property" ||
      property.kind !== "init" ||
      property.computed ||
      property.key.type !== "Identifier"
    ) {
      throw new Error("React DevTools contains an unsupported work-tag property");
    }
    workTags[property.key.name] = readWorkTagValue(property.value);
  }
  return workTags;
};

const readReactDevToolsWorkTags = (): WorkTags[] => {
  const require = createRequire(import.meta.url);
  const packagePath = require.resolve("react-devtools-core/package.json");
  const backendPath = resolve(dirname(packagePath), "dist/backend.js");
  const parseResult = parseSync(backendPath, readFileSync(backendPath, "utf8"), {
    lang: "js",
    sourceType: "script",
  });
  if (parseResult.errors.length > 0) {
    throw new Error(`Oxc could not parse React DevTools: ${parseResult.errors[0]?.message}`);
  }

  const workTagMaps: WorkTags[] = [];
  new Visitor({
    AssignmentExpression: (expression) => {
      if (
        expression.left.type === "Identifier" &&
        expression.left.name === "ReactTypeOfWork" &&
        expression.right.type === "ObjectExpression"
      ) {
        workTagMaps.push(readWorkTags(expression.right));
      }
    },
  }).visit(parseResult.program);

  if (workTagMaps.length < 2) {
    throw new Error("React DevTools does not contain the expected work-tag tables");
  }
  return workTagMaps;
};

const validateWorkTags = (
  react17Point0Point2WorkTags: WorkTags,
  react17Point0Point1WorkTags: WorkTags,
): string[] => {
  const react17Point0Point2Names = Object.keys(react17Point0Point2WorkTags).sort();
  const react17Point0Point1Names = Object.keys(react17Point0Point1WorkTags).sort();
  if (
    react17Point0Point2Names.length === 0 ||
    react17Point0Point2Names.join("\0") !== react17Point0Point1Names.join("\0")
  ) {
    throw new Error("React DevTools work-tag tables are empty or have mismatched keys");
  }
  return react17Point0Point2Names;
};

const renderWorkTagMap = (version: string, names: string[], workTags: WorkTags): string =>
  [
    `  "${version}": {`,
    ...names.map((workTagName) => `    ${workTagName}: ${workTags[workTagName]},`),
    "  },",
  ].join("\n");

const renderWorkTagConstant = (name: string): string => {
  const declaration = `export const ${name}Tag = react17Point0Point2WorkTags.${name};`;
  return declaration.length <= generatedModuleLineWidth
    ? declaration
    : `export const ${name}Tag =\n  react17Point0Point2WorkTags.${name};`;
};

const renderGeneratedModule = (
  names: string[],
  react17Point0Point2WorkTags: WorkTags,
  react17Point0Point1WorkTags: WorkTags,
): string => {
  const constants = names
    .filter((name) => react17Point0Point2WorkTags[name] >= 0)
    .map(renderWorkTagConstant)
    .join("\n");

  return [
    "// Generated by the React internals Vite+ plugin from react-devtools-core.",
    "",
    "export interface ReactWorkTagMap {",
    ...names.map((name) => `  ${name}: number;`),
    "}",
    "",
    "const defineReactWorkTags = <const VersionedWorkTags extends Record<string, ReactWorkTagMap>>(",
    "  workTags: VersionedWorkTags,",
    "): VersionedWorkTags => workTags;",
    "",
    "export const ReactWorkTags = defineReactWorkTags({",
    renderWorkTagMap("17.0.1", names, react17Point0Point1WorkTags),
    renderWorkTagMap("17.0.2", names, react17Point0Point2WorkTags),
    "});",
    "",
    "export type ReactWorkTagVersion = keyof typeof ReactWorkTags;",
    "",
    'const react17Point0Point2WorkTags = ReactWorkTags["17.0.2"];',
    "",
    constants,
    "",
    "export type ReactWorkTag = Exclude<",
    "  (typeof ReactWorkTags)[ReactWorkTagVersion][keyof ReactWorkTagMap],",
    "  -1",
    ">;",
    "",
    "export type HostWorkTag =",
    "  | typeof HostComponentTag",
    "  | typeof HostHoistableTag",
    "  | typeof HostSingletonTag",
    "  | typeof HostTextTag;",
    "",
    "export const getReactWorkTags = (version: string): Readonly<ReactWorkTagMap> =>",
    '  /^17\\.0\\.1(?:\\D|$)/.test(version) ? ReactWorkTags["17.0.1"] : ReactWorkTags["17.0.2"];',
    "",
  ].join("\n");
};

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const generatedModulePath = resolve(scriptDirectory, "../src/generated/react-work-tags.ts");

const generateReactInternals = (): void => {
  const [react17Point0Point2WorkTags, react17Point0Point1WorkTags] = readReactDevToolsWorkTags();
  const names = validateWorkTags(react17Point0Point2WorkTags, react17Point0Point1WorkTags);
  const generatedModule = renderGeneratedModule(
    names,
    react17Point0Point2WorkTags,
    react17Point0Point1WorkTags,
  );
  const existingModule = existsSync(generatedModulePath)
    ? readFileSync(generatedModulePath, "utf8")
    : undefined;

  if (existingModule === generatedModule) return;
  if (process.env.CI) {
    throw new Error("Generated React internals are stale; run nr build and commit the result");
  }
  mkdirSync(dirname(generatedModulePath), { recursive: true });
  writeFileSync(generatedModulePath, generatedModule);
};

export const reactInternalsPlugin = (): Plugin => {
  let didGenerateReactInternals = false;
  return {
    name: "bippy-react-internals",
    buildStart: () => {
      if (didGenerateReactInternals) return;
      generateReactInternals();
      didGenerateReactInternals = true;
    },
  };
};
