import { readFileSync } from "node:fs";
import path from "node:path";
import {
  decodeHostRealmTable,
  GLOBAL_INTERFACE_NAME,
  GLOBAL_OBJECT_TYPE,
  type HostInterface,
  type HostMember,
  type HostRealmTable,
  type HostType,
  type HostValueKind,
} from "./realm-table.js";

/** Declared names include `constructor` and `toString`, which plain-object indexing would find on `Object.prototype`. */
const getOwnEntry = <Entry>(record: Record<string, Entry>, key: string): Entry | null =>
  Object.hasOwn(record, key) ? record[key] : null;

/** `"buffer".Blob` -> `Blob`: module-scoped declarations carry their module as a qualifier. */
const getUnqualifiedName = (interfaceName: string): string =>
  interfaceName.replace(/^"[^"]*"\./, "");

export type HostPlatform = "ecmascript" | "browser" | "node" | "react-native";

export const HOST_PLATFORMS: readonly HostPlatform[] = [
  "ecmascript",
  "browser",
  "node",
  "react-native",
];

export const REALMS_DIRECTORY = path.join(import.meta.dirname, "realms");

export const getRealmTablePath = (platform: HostPlatform): string =>
  path.join(REALMS_DIRECTORY, `${platform}.json`);

export const getRealmGapReportPath = (platform: HostPlatform): string =>
  path.join(REALMS_DIRECTORY, `${platform}.gaps.json`);

/**
 * Which globals a JavaScript host provides and what they are, read from the
 * platform's declaration files (generated by `scripts/generate-host-realms.ts`)
 * rather than listed by hand. Capabilities declarations cannot express (a live
 * document, storage state, layout) are the evaluator's semantic adapters.
 */
export class HostRealm {
  private readonly memberCache = new Map<string, HostMember | null>();
  private memberReturnKinds: Map<string, HostValueKind | null> | null = null;

  constructor(
    readonly platform: HostPlatform,
    private readonly table: HostRealmTable,
  ) {}

  /** Whether the host has a browser DOM: `document`, HTML elements and layout. */
  get hasDocument(): boolean {
    return this.platform === "browser";
  }

  /** A global by dotted path (`Intl.DateTimeFormat`, `window.document.body`); `null` when undeclared. */
  getGlobal(name: string): HostMember | null {
    let member: HostMember | null = { type: GLOBAL_OBJECT_TYPE, returnType: null };
    for (const key of name.split(".")) {
      const interfaceName: string | null = member.type.interfaceName;
      if (interfaceName === null) return null;
      member = this.isGlobalObjectType(member.type)
        ? this.getGlobalObjectMember(key)
        : this.getMember(interfaceName, key);
      if (member === null) return null;
    }
    return member;
  }

  hasGlobal(name: string): boolean {
    return this.getGlobal(name) !== null;
  }

  /** The `typeof` a declared global evaluates to, `"undefined"` for another host's global, null when open. */
  getGlobalTypeof(name: string): string | null {
    const member = this.getGlobal(name);
    if (member === null) return this.isForeignGlobal(name) ? "undefined" : null;
    const kind = this.getTypeKind(member.type);
    return kind === "any" || member.type.isNullable ? null : kind;
  }

  /**
   * A global another host provides and this one lacks (`document` in Node), so
   * reading it is decided. A name no host declares may still be injected by a
   * script, so it stays open.
   */
  isForeignGlobal(name: string): boolean {
    return (
      !this.hasGlobal(name) &&
      HOST_PLATFORMS.some(
        (platform) => platform !== this.platform && loadHostRealm(platform).hasGlobal(name),
      )
    );
  }

  /** The runtime `typeof` of a declared type; `Function` and its subtypes are callable even though declarations describe them as objects. */
  getTypeKind(type: HostType): HostValueKind {
    return type.kind === "object" &&
      type.interfaceName !== null &&
      this.isSubtype(type.interfaceName, "Function")
      ? "function"
      : type.kind;
  }

  /** Whether the global names an instance of `ancestorName`, or a class whose instances are. */
  isGlobalInstanceOf(name: string, ancestorName: string): boolean {
    const member = this.getGlobal(name);
    if (member === null) return false;
    const instanceType = this.isGlobalObjectType(member.type)
      ? null
      : (this.getGlobal(`${name}.prototype`)?.type ?? member.type);
    if (instanceType === null) {
      return this.table.globalObjectInterfaces.some((interfaceName) =>
        this.isSubtype(interfaceName, ancestorName),
      );
    }
    return (
      instanceType.interfaceName !== null &&
      this.isSubtype(instanceType.interfaceName, ancestorName)
    );
  }

  /** The `typeof` every declared method of this name returns, or null when interfaces disagree or none declares it. */
  getMemberReturnKind(memberName: string): HostValueKind | null {
    this.memberReturnKinds ??= this.collectMemberReturnKinds();
    return this.memberReturnKinds.get(memberName) ?? null;
  }

  /** A member declared on an interface or inherited from what it extends. */
  getMember(interfaceName: string, memberName: string): HostMember | null {
    const cacheKey = `${interfaceName}\0${memberName}`;
    const cached = this.memberCache.get(cacheKey);
    if (cached !== undefined) return cached;
    const member = this.findMember(interfaceName, memberName, new Set());
    this.memberCache.set(cacheKey, member);
    return member;
  }

  /** Whether `name` (`window`, `self`, `global`, `globalThis`) is the global object itself on this host. */
  isGlobalAlias(name: string): boolean {
    const member = this.getGlobal(name);
    return member !== null && this.isGlobalObjectType(member.type);
  }

  /** Strips leading global-object aliases: `window.document.body` -> `document.body`. */
  normalizeGlobalName(name: string): string {
    let normalized = name;
    for (let separator = normalized.indexOf("."); separator !== -1;) {
      if (!this.isGlobalAlias(normalized.slice(0, separator))) break;
      normalized = normalized.slice(separator + 1);
      separator = normalized.indexOf(".");
    }
    return normalized;
  }

  getInterface(interfaceName: string): HostInterface | null {
    return getOwnEntry(this.table.interfaces, interfaceName);
  }

  isGlobalObjectType(type: HostType): boolean {
    return (
      type.interfaceName !== null &&
      (type.interfaceName === GLOBAL_INTERFACE_NAME ||
        this.table.globalObjectInterfaces.includes(type.interfaceName))
    );
  }

  /** Whether the interface is, or extends, one named `ancestorName` (unqualified, so a module's own `EventTarget` counts). */
  isSubtype(interfaceName: string, ancestorName: string): boolean {
    const pending = [interfaceName];
    const seen = new Set<string>();
    for (let current = pending.pop(); current !== undefined; current = pending.pop()) {
      if (seen.has(current)) continue;
      seen.add(current);
      if (getUnqualifiedName(current) === ancestorName) return true;
      const record = this.getInterface(current);
      if (record) pending.push(...record.extendsNames);
    }
    return false;
  }

  private collectMemberReturnKinds(): Map<string, HostValueKind | null> {
    const kinds = new Map<string, HostValueKind | null>();
    for (const record of Object.values(this.table.interfaces)) {
      for (const [memberName, member] of Object.entries(record.members)) {
        if (member.type.kind !== "function" || member.returnType === null) continue;
        const returnKind =
          member.returnType.kind === "any" || member.returnType.isNullable
            ? null
            : this.getTypeKind(member.returnType);
        const known = kinds.get(memberName);
        kinds.set(memberName, known === undefined || known === returnKind ? returnKind : null);
      }
    }
    return kinds;
  }

  private getGlobalObjectMember(key: string): HostMember | null {
    if (key === GLOBAL_INTERFACE_NAME) return { type: GLOBAL_OBJECT_TYPE, returnType: null };
    for (const interfaceName of this.table.globalObjectInterfaces) {
      const member = this.getMember(interfaceName, key);
      if (member) return member;
    }
    return this.getMember(GLOBAL_INTERFACE_NAME, key);
  }

  private findMember(
    interfaceName: string,
    memberName: string,
    seen: Set<string>,
  ): HostMember | null {
    if (seen.has(interfaceName)) return null;
    seen.add(interfaceName);
    const record = this.getInterface(interfaceName);
    if (!record) return null;
    const own = getOwnEntry(record.members, memberName);
    if (own) return own;
    for (const parent of record.extendsNames) {
      const inherited = this.findMember(parent, memberName, seen);
      if (inherited) return inherited;
    }
    return null;
  }
}

const realmCache = new Map<HostPlatform, HostRealm>();

export const loadHostRealm = (platform: HostPlatform): HostRealm => {
  let realm = realmCache.get(platform);
  if (!realm) {
    const json: unknown = JSON.parse(readFileSync(getRealmTablePath(platform), "utf8"));
    realm = new HostRealm(platform, decodeHostRealmTable(json));
    realmCache.set(platform, realm);
  }
  return realm;
};
