import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  decodeHostRealmTable,
  GLOBAL_INTERFACE_NAME,
  GLOBAL_OBJECT_TYPE,
  type HostMember,
  type HostRealmTable,
  type HostType,
} from "./realm-table.js";

export type HostPlatform = "ecmascript" | "browser" | "node" | "react-native";

export const HOST_PLATFORMS: readonly HostPlatform[] = [
  "ecmascript",
  "browser",
  "node",
  "react-native",
];

export const REALMS_DIRECTORY = fileURLToPath(new URL("./realms/", import.meta.url));

export const getRealmTablePath = (platform: HostPlatform): string =>
  path.join(REALMS_DIRECTORY, `${platform}.json`);

/**
 * Which globals a JavaScript host provides and what they are, read from the
 * platform's declaration files (generated by `scripts/generate-host-realms.ts`)
 * rather than listed by hand. Capabilities declarations cannot express (a live
 * document, storage state, layout) are the evaluator's semantic adapters.
 */
export class HostRealm {
  private readonly memberCache = new Map<string, HostMember | null>();

  constructor(
    readonly platform: HostPlatform,
    private readonly table: HostRealmTable,
  ) {}

  /** Whether the host has a browser DOM: `document`, HTML elements and layout. */
  get hasDocument(): boolean {
    return this.platform === "browser";
  }

  /** A global by dotted path (`Intl.DateTimeFormat`, `window.document.body`); `null` when undeclared. */
  getGlobal(name: string): HostMember | null {
    let member: HostMember | null = { type: GLOBAL_OBJECT_TYPE, returnType: null };
    for (const key of name.split(".")) {
      const interfaceName: string | null = member.type.interfaceName;
      if (interfaceName === null) return null;
      member = this.isGlobalObjectType(member.type)
        ? this.getGlobalObjectMember(key)
        : this.getMember(interfaceName, key);
      if (member === null) return null;
    }
    return member;
  }

  hasGlobal(name: string): boolean {
    return this.getGlobal(name) !== null;
  }

  /** The `typeof` a declared global evaluates to, or `"undefined"` when the host lacks it. */
  getGlobalTypeof(name: string): string | null {
    const member = this.getGlobal(name);
    if (member === null) return "undefined";
    return member.type.kind === "any" || member.type.isNullable ? null : member.type.kind;
  }

  /** A member declared on an interface or inherited from what it extends. */
  getMember(interfaceName: string, memberName: string): HostMember | null {
    const cacheKey = `${interfaceName}\0${memberName}`;
    const cached = this.memberCache.get(cacheKey);
    if (cached !== undefined) return cached;
    const member = this.findMember(interfaceName, memberName, new Set());
    this.memberCache.set(cacheKey, member);
    return member;
  }

  /** Whether `name` (`window`, `self`, `global`, `globalThis`) is the global object itself on this host. */
  isGlobalAlias(name: string): boolean {
    const member = this.getGlobal(name);
    return member !== null && this.isGlobalObjectType(member.type);
  }

  /** Strips leading global-object aliases: `window.document.body` -> `document.body`. */
  normalizeGlobalName(name: string): string {
    let normalized = name;
    for (let separator = normalized.indexOf("."); separator !== -1;) {
      if (!this.isGlobalAlias(normalized.slice(0, separator))) break;
      normalized = normalized.slice(separator + 1);
      separator = normalized.indexOf(".");
    }
    return normalized;
  }

  isGlobalObjectType(type: HostType): boolean {
    return (
      type.interfaceName !== null &&
      (type.interfaceName === GLOBAL_INTERFACE_NAME ||
        this.table.globalObjectInterfaces.includes(type.interfaceName))
    );
  }

  isSubtype(interfaceName: string, ancestorName: string): boolean {
    const pending = [interfaceName];
    const seen = new Set<string>();
    for (let current = pending.pop(); current !== undefined; current = pending.pop()) {
      if (seen.has(current)) continue;
      seen.add(current);
      if (current === ancestorName) return true;
      const record = this.table.interfaces[current];
      if (record) pending.push(...record.extendsNames);
    }
    return false;
  }

  private getGlobalObjectMember(key: string): HostMember | null {
    if (key === GLOBAL_INTERFACE_NAME) return { type: GLOBAL_OBJECT_TYPE, returnType: null };
    for (const interfaceName of this.table.globalObjectInterfaces) {
      const member = this.getMember(interfaceName, key);
      if (member) return member;
    }
    return this.getMember(GLOBAL_INTERFACE_NAME, key);
  }

  private findMember(
    interfaceName: string,
    memberName: string,
    seen: Set<string>,
  ): HostMember | null {
    if (seen.has(interfaceName)) return null;
    seen.add(interfaceName);
    const record = this.table.interfaces[interfaceName];
    if (!record) return null;
    const own = record.members[memberName];
    if (own) return own;
    for (const parent of record.extendsNames) {
      const inherited = this.findMember(parent, memberName, seen);
      if (inherited) return inherited;
    }
    return null;
  }
}

const realmCache = new Map<HostPlatform, HostRealm>();

export const loadHostRealm = (platform: HostPlatform): HostRealm => {
  let realm = realmCache.get(platform);
  if (!realm) {
    const json: unknown = JSON.parse(readFileSync(getRealmTablePath(platform), "utf8"));
    realm = new HostRealm(platform, decodeHostRealmTable(json));
    realmCache.set(platform, realm);
  }
  return realm;
};
