name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: curl -fsSL https://vite.plus | bash
      - run: npm i -g --force corepack && corepack enable
      - uses: pnpm/action-setup@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm check
